# Generated by Django 5.2.5 on 2025-08-14 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('google_reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=100)),
                ('family_friendly', models.BooleanField(default=False)),
                ('convenience', models.CharField(blank=True, max_length=100)),
                ('price_per_person', models.CharField(blank=True, max_length=50)),
                ('newly_opened', models.BooleanField(default=False)),
                ('local_rating', models.CharField(blank=True, max_length=20)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('company_ranking', models.CharField(blank=True, max_length=50)),
                ('highlights', models.TextField(blank=True)),
                ('top_picks', models.TextField(blank=True)),
                ('top_rated_comments', models.TextField(blank=True)),
                ('recent_comments', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='myapp.category')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='myapp.page')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='myapp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='myapp.platform'),
        ),
    ]
